#plot histograms of residuals and significant correlations


library(rcompanion)

provinces(list_ASVCounts$ASVCount_16S.tax.auto.hellinger, list_meta$meta_functions.z)

corr_plot_residuals(meta_FKLD[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_NO3_umol.l, main = "auto.euk - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.euk_PO4_umol.l, main = "auto.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_chlorophyll, main = "auto.cyano - chl a")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_salinity, main = "auto.cyano - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_distance_to_province_boundary.km., main = "auto.cyano - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Distance_coast.km., main = "auto.cyano - Distance coast")
plotNormalHistogram(a.residuals$Shannon.mixo_chlorophyll, main = "mixo - chl a")
plotNormalHistogram(a.residuals$Shannon.mixo_salinity, main = "mixo - salinity")
plotNormalHistogram(a.residuals$Shannon.mixo_distance_to_province_boundary.km., main = "mixo - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.mixo_Distance_coast.km., main = "mixo - Distance coast")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.het.euk, main = "mixo - het.euk")
plotNormalHistogram(a.residuals$Shannon.het.euk_chlorophyll, main = "het.euk - chl a")
plotNormalHistogram(a.residuals$Shannon.het.euk_salinity, main = "het.euk - salinity")
plotNormalHistogram(a.residuals$Shannon.het.euk_distance_to_province_boundary.km., main = "het.euk - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.het.euk_Distance_coast.km., main = "het.euk - Distance Coast")
plotNormalHistogram(a.residuals$Shannon.het.euk_Shannon.auto.cynao, main = "het.euk - auto.cyano")
#
corr_plot_residuals(meta_BRAZ[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_SST, main = "auto.euk - temp")
plotNormalHistogram(a.residuals$Shannon.auto.euk_salinity, main = "auto.euk - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.euk_NO3_umol.l, main = "auto.euk - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.euk_oxygen.umol.l., main = "auto.euk - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.euk_PO4_umol.l, main = "auto.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.C..nmol.L., main = "auto.euk - POC")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.N..nmol.L., main = "auto.euk - PN")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Shannon.auto.euk, main = "auto.cyano - auto.euk")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_SST, main = "auto.cyano - SST")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_salinity, main = "auto.cyano - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_oxygen.umol.l., main = "auto.cyano - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_NO3_umol.l, main = "auto.cyano - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_PO4_umol.l, main = "auto.cyano - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.C..nmol.L., main = "auto.cyano - POC")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.N..nmol.L., main = "auto.cyano - PN")
plotNormalHistogram(a.residuals$Shannon.mixo_salinity, main = "mixo - salinity")
plotNormalHistogram(a.residuals$Shannon.mixo_PO4_umol.l, main = "mixo - PO4")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.het.euk, main = "mixo - het.euk")
plotNormalHistogram(a.residuals$Shannon.het.euk_Shannon.auto.cynao, main = "het.euk - auto.cyano")
plotNormalHistogram(a.residuals$Shannon.het.euk_SST, main = "het.euk - SST")
plotNormalHistogram(a.residuals$Shannon.het.euk_oxygen.umol.l., main = "het.euk - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.euk_NO3_umol.l, main = "het.euk - NO3")
plotNormalHistogram(a.residuals$Shannon.het.euk_PO4_umol.l, main = "het.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.het.prok_Shannon.auto.cynao, main = "het.prok - auto.cyano")
plotNormalHistogram(a.residuals$Shannon.het.prok_Shannon.auto.euk, main = "het.prok - auto.euk")
plotNormalHistogram(a.residuals$Shannon.het.prok_SST, main = "het.prok - SST")
plotNormalHistogram(a.residuals$Shannon.het.prok_salinity, main = "het.prok - salinity")
plotNormalHistogram(a.residuals$Shannon.het.prok_oxygen.umol.l., main = "het.prok - oxygen")

corr_plot_residuals(meta_SATL_cold[subselection])
plotNormalHistogram(a.residuals$SST_Shannon.auto.euk, main = "auto.euk - SST")
plotNormalHistogram(a.residuals$Shannon.auto.euk_oxygen.umol.l., main = "auto.euk - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.C..nmol.L., main = "auto.euk - POC")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.N..nmol.L., main = "auto.euk - PN")
plotNormalHistogram(a.residuals$Shannon.auto.euk_chlorophyll, main = "auto.euk - chl a")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Shannon.auto.euk, main = "auto.cyano - auto.euk")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_distance_to_province_boundary.km., main = "auto.cyano - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_SST, main = "auto.cyano - SST")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_salinity, main = "auto.cyano - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_oxygen.umol.l., main = "auto.cyano - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.C..nmol.L., main = "auto.cyano - POC")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.N..nmol.L., main = "auto.cyano - PN")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_chlorophyll, main = "auto.cyano - chl a")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.auto.euk, main = "mixo - auto.euk")
plotNormalHistogram(a.residuals$Shannon.mixo_NO3_umol.l, main = "mixo - NO3")
plotNormalHistogram(a.residuals$Shannon.mixo_Si_umol.l, main = "mixo - Si")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.het.euk, main = "mixo - het.euk")
plotNormalHistogram(a.residuals$Shannon.het.prok_Shannon.auto.cynao, main = "het.prok - auto.cyano")
plotNormalHistogram(a.residuals$Shannon.het.prok_Shannon.auto.euk, main = "het.prok - auto.euk")
plotNormalHistogram(a.residuals$Shannon.het.prok_Total.N..nmol.L., main = "het.prok - PN")

corr_plot_residuals(meta_SATL_hot[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_NO3_umol.l, main = "auto.euk - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Shannon.mixo, main = "auto.euk - mixo")
plotNormalHistogram(a.residuals$Shannon.het.euk_Shannon.mixo, main = "het.euk - mixo")
plotNormalHistogram(a.residuals$Shannon.het.euk_Shannon.auto.euk, main = "het.euk - auto.euk")
plotNormalHistogram(a.residuals$Shannon.het.euk_chlorophyll, main = "het.euk - chl a")
plotNormalHistogram(a.residuals$Shannon.het.prok_Distance_coast.km., main = "het.prok - Distance coast")
plotNormalHistogram(a.residuals$Shannon.het.prok_Si_umol.l, main = "het.prok - Si")
plotNormalHistogram(a.residuals$Shannon.het.prok_chlorophyll, main = "het.prok - chl a")

corr_plot_residuals(meta_WTRA[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_Distance_coast.km., main = "auto.euk - Distance coast")
plotNormalHistogram(a.residuals$Shannon.auto.euk_distance_to_province_boundary.km., main = "auto.euk - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.auto.euk_PO4_umol.l, main = "auto.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_SST, main = "auto.cyano - SST")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.N..nmol.L., main = "auto.cyano - PN")
plotNormalHistogram(a.residuals$Shannon.mixo_SST, main = "mixo - SST")
plotNormalHistogram(a.residuals$Shannon.mixo_salinity, main = "mixo - salinity")
plotNormalHistogram(a.residuals$Shannon.het.euk_Distance_coast.km., main = "het.euk - Distance coast")
plotNormalHistogram(a.residuals$Shannon.het.euk_distance_to_province_boundary.km., main = "het.euk - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.het.euk_SST, main = "het.euk - SST")
plotNormalHistogram(a.residuals$Shannon.het.euk_oxygen.umol.l., main = "het.euk - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.prok_Distance_coast.km., main = "het.prok - Distance coast")
plotNormalHistogram(a.residuals$Shannon.het.prok_distance_to_province_boundary.km., main = "het.prok - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.het.prok_SST, main = "het.prok - SST")
plotNormalHistogram(a.residuals$Shannon.het.prok_oxygen.umol.l., main = "het.prok - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.prok_PO4_umol.l, main = "het.prok - PO4")

corr_plot_residuals(meta_NATR[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.cynao_PO4_umol.l, main = "auto.cyano - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.C..nmol.L., main = "auto.cyano - POC")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Shannon.mixo, main = "auto.cyano - mixo")
plotNormalHistogram(a.residuals$Shannon.mixo_Distance_coast.km., main = "mixo - Distance coast")
plotNormalHistogram(a.residuals$Shannon.mixo_SST, main = "mixo - SST")
plotNormalHistogram(a.residuals$Shannon.mixo_salinity, main = "mixo - salinity")
plotNormalHistogram(a.residuals$Shannon.mixo_oxygen.umol.l., main = "mixo - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.prok_distance_to_province_boundary.km., main = "het.prok - distance.province.boundary")

corr_plot_residuals(meta_CNRY[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_Distance_coast.km., main = "auto.euk - Distance coast")
plotNormalHistogram(a.residuals$Shannon.auto.euk_distance_to_province_boundary.km., main = "auto.euk - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.auto.euk_SST, main = "auto.euk - SST")
plotNormalHistogram(a.residuals$Shannon.auto.euk_salinity, main = "auto.euk - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.euk_PO4_umol.l, main = "auto.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.C..nmol.L., main = "auto.euk - POC")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.N..nmol.L., main = "auto.euk - PN")
plotNormalHistogram(a.residuals$Shannon.auto.euk_chlorophyll, main = "auto.euk - chl a")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Shannon.auto.cynao, main = "auto.euk - auto.cyano")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Distance_coast.km., main = "auto.cyano - Distance coast")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_distance_to_province_boundary.km., main = "auto.cyano - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_SST, main = "auto.cyano - SST")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_salinity, main = "auto.cyano - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_NO3_umol.l, main = "auto.cyano - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_PO4_umol.l, main = "auto.cyano - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.C..nmol.L., main = "auto.cyano - POC")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.N..nmol.L., main = "auto.cyano - PN")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_chlorophyll, main = "auto.cyano - chl a")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.auto.cynao, main = "mixo - auto.cyano")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.auto.euk, main = "mixo - auto.euk")
plotNormalHistogram(a.residuals$Shannon.mixo_Distance_coast.km., main = "mixo - Distance coast")
plotNormalHistogram(a.residuals$Shannon.mixo_distance_to_province_boundary.km., main = "mixo - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.mixo_salinity, main = "mixo - salinity")
plotNormalHistogram(a.residuals$Shannon.mixo_NO3_umol.l, main = "mixo - NO3")
plotNormalHistogram(a.residuals$Shannon.mixo_PO4_umol.l, main = "mixo - PO4")
plotNormalHistogram(a.residuals$Shannon.het.euk_salinity, main = "het.euk - salinity")
plotNormalHistogram(a.residuals$Shannon.het.prok_oxygen.umol.l., main = "het.prok - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.prok_Si_umol.l, main = "het.prok - Si")


corr_plot_residuals(meta_NAST[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_oxygen.umol.l., main = "auto.euk - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.euk_PO4_umol.l, main = "auto.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Si_umol.l, main = "auto.euk - Si")
plotNormalHistogram(a.residuals$Shannon.auto.euk_chlorophyll, main = "auto.euk - chl a")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_SST, main = "auto.cyano - SST")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_oxygen.umol.l., main = "auto.cyano - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_NO3_umol.l, main = "auto.cyano - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_PO4_umol.l, main = "auto.cyano - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Si_umol.l, main = "auto.cyano - Si")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.C..nmol.L., main = "auto.cyano - POC")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_chlorophyll, main = "auto.cyano - chl a")
plotNormalHistogram(a.residuals$Shannon.mixo_SST, main = "mixo - SST")
plotNormalHistogram(a.residuals$Shannon.mixo_salinity, main = "mixo - salinity")
plotNormalHistogram(a.residuals$Shannon.mixo_oxygen.umol.l., main = "mixo - oxygen")
plotNormalHistogram(a.residuals$Shannon.mixo_NO3_umol.l, main = "mixo - NO3")
plotNormalHistogram(a.residuals$Shannon.mixo_PO4_umol.l, main = "mixo - PO4")
plotNormalHistogram(a.residuals$Shannon.mixo_Si_umol.l, main = "mixo - Si")


corr_plot_residuals(meta_NADR[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.C..nmol.L., main = "auto.euk - POC")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.N..nmol.L., main = "auto.euk - PN")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_distance_to_province_boundary.km., main = "auto.cyano - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_salinity, main = "auto.cyano - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.C..nmol.L., main = "auto.cyano - POC")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.N..nmol.L., main = "auto.cyano - PN")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_chlorophyll, main = "auto.cyano - chl a")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.auto.euk, main = "mixo - auto.euk")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.het.euk, main = "mixo - het.euk")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Shannon.het.euk, main = "auto.euk - het.euk")
plotNormalHistogram(a.residuals$Shannon.het.euk_Distance_coast.km., main = "het.euk - Distance coast")
plotNormalHistogram(a.residuals$Shannon.het.euk_SST, main = "het.euk - SST")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.het.prok, main = "mixo - het.prok")
plotNormalHistogram(a.residuals$Shannon.het.prok_oxygen.umol.l., main = "het.prok - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.prok_PO4_umol.l, main = "het.prok - PO4")
plotNormalHistogram(a.residuals$Shannon.het.prok_Total.C..nmol.L., main = "het.prok - POC")

corr_plot_residuals(list_meta$meta_functions.z[subselection])
plotNormalHistogram(a.residuals$Shannon.auto.euk_Distance_coast.km., main = "auto.euk - Distance coast")
plotNormalHistogram(a.residuals$Shannon.auto.euk_distance_to_province_boundary.km., main = "auto.euk - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.auto.euk_SST, main = "auto.euk - SST")
plotNormalHistogram(a.residuals$Shannon.auto.euk_salinity, main = "auto.euk - salinity")
plotNormalHistogram(a.residuals$Shannon.auto.euk_oxygen.umol.l., main = "auto.euk - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.euk_NO3_umol.l, main = "auto.euk - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.euk_PO4_umol.l, main = "auto.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.C..nmol.L., main = "auto.euk - POC")
plotNormalHistogram(a.residuals$Shannon.auto.euk_Total.N..nmol.L., main = "auto.euk - PN")
plotNormalHistogram(a.residuals$Shannon.auto.euk_chlorophyll, main = "auto.euk - chl a")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_oxygen.umol.l., main = "auto.cyano - oxygen")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_NO3_umol.l, main = "auto.cyano - NO3")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_PO4_umol.l, main = "auto.cyano - PO4")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.C..nmol.L., main = "auto.cyano - POC")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Total.N..nmol.L., main = "auto.cyano - PN")
plotNormalHistogram(a.residuals$Shannon.auto.cynao_Shannon.mixo, main = "auto.cyano - mixo")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.auto.euk, main = "mixo - auto.euk")
plotNormalHistogram(a.residuals$Shannon.mixo_Distance_coast.km., main = "mixo - Distance coast")
plotNormalHistogram(a.residuals$Shannon.mixo_distance_to_province_boundary.km., main = "mixo - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.mixo_SST, main = "mixo - SST")
plotNormalHistogram(a.residuals$Shannon.mixo_salinity, main = "het.euk - SST")
plotNormalHistogram(a.residuals$Shannon.mixo_oxygen.umol.l., main = "mixo - salinity")
plotNormalHistogram(a.residuals$Shannon.mixo_NO3_umol.l, main = "mixo - NO3")
plotNormalHistogram(a.residuals$Shannon.mixo_PO4_umol.l, main = "mixo - PO4")
plotNormalHistogram(a.residuals$Shannon.mixo_Total.C..nmol.L., main = "mixo - POC")
plotNormalHistogram(a.residuals$Shannon.mixo_Total.N..nmol.L., main = "mixo - PN")
plotNormalHistogram(a.residuals$Shannon.mixo_chlorophyll, main = "mixo - chl a")
plotNormalHistogram(a.residuals$Shannon.mixo_Shannon.het.euk, main = "mixo - het.euk")
plotNormalHistogram(a.residuals$Shannon.het.euk_Shannon.auto.cynao, main = "het.euk - auto.cyano")
plotNormalHistogram(a.residuals$Shannon.het.euk_Shannon.auto.euk, main = "het.euk - auto.euk")
plotNormalHistogram(a.residuals$Shannon.het.euk_Distance_coast.km., main = "het.euk - Distance coast")
plotNormalHistogram(a.residuals$Shannon.het.euk_distance_to_province_boundary.km., main = "het.euk - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.het.euk_SST, main = "het.euk - SST")
plotNormalHistogram(a.residuals$Shannon.het.euk_salinity, main = "het.euk - salinity")
plotNormalHistogram(a.residuals$Shannon.het.euk_oxygen.umol.l., main = "het.euk - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.euk_NO3_umol.l, main = "het.euk - NO3")
plotNormalHistogram(a.residuals$Shannon.het.euk_PO4_umol.l, main = "het.euk - PO4")
plotNormalHistogram(a.residuals$Shannon.het.euk_Total.C..nmol.L., main = "het.euk - POC")
plotNormalHistogram(a.residuals$Shannon.het.euk_Total.N..nmol.L., main = "het.euk - PN")
plotNormalHistogram(a.residuals$Shannon.het.euk_chlorophyll, main = "het.euk - chl a")
plotNormalHistogram(a.residuals$Shannon.het.euk_Shannon.het.prok, main = "het.euk - het.prok")
plotNormalHistogram(a.residuals$Shannon.het.prok_Shannon.mixo, main = "het.prok - mixo")
plotNormalHistogram(a.residuals$Shannon.het.prok_Distance_coast.km., main = "het.prok - Distance coast")
plotNormalHistogram(a.residuals$Shannon.het.prok_distance_to_province_boundary.km., main = "het.prok - distance.province.boundary")
plotNormalHistogram(a.residuals$Shannon.het.prok_SST, main = "het.prok - SST")
plotNormalHistogram(a.residuals$Shannon.het.prok_salinity, main = "het.prok - salinity")
plotNormalHistogram(a.residuals$Shannon.het.prok_oxygen.umol.l., main = "het.prok - oxygen")
plotNormalHistogram(a.residuals$Shannon.het.prok_NO3_umol.l, main = "het.prok - NO3")
plotNormalHistogram(a.residuals$Shannon.het.prok_PO4_umol.l, main = "het.prok - PO4")
plotNormalHistogram(a.residuals$Shannon.het.prok_Total.C..nmol.L., main = "het.prok - POC")
plotNormalHistogram(a.residuals$Shannon.het.prok_Total.N..nmol.L., main = "het.prok - PN")
plotNormalHistogram(a.residuals$Shannon.het.prok_chlorophyll, main = "het.prok - chl a")


#correlation plots

plot_correlations(meta_BRAZ,meta_BRAZ$SST, meta_BRAZ$Shannon.auto.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$salinity, meta_BRAZ$Shannon.auto.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$oxygen.umol.l., meta_BRAZ$Shannon.auto.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$NO3_umol.l, meta_BRAZ$Shannon.auto.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$Total.C..nmol.L., meta_BRAZ$Shannon.auto.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$Total.N..nmol.L., meta_BRAZ$Shannon.auto.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$Shannon.auto.cynao, meta_BRAZ$Shannon.auto.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$SST, meta_BRAZ$Shannon.auto.cynao)
plot_correlations(meta_BRAZ,meta_BRAZ$salinity, meta_BRAZ$Shannon.auto.cynao)
plot_correlations(meta_BRAZ,meta_BRAZ$oxygen.umol.l., meta_BRAZ$Shannon.auto.cynao)
plot_correlations(meta_BRAZ,meta_BRAZ$NO3_umol.l, meta_BRAZ$Shannon.auto.cynao)
plot_correlations(meta_BRAZ,meta_BRAZ$PO4_umol.l, meta_BRAZ$Shannon.auto.cynao)
plot_correlations(meta_BRAZ,meta_BRAZ$Total.N..nmol.L., meta_BRAZ$Shannon.auto.cynao)
plot_correlations(meta_BRAZ,meta_BRAZ$salinity, meta_BRAZ$Shannon.mixo)
plot_correlations(meta_BRAZ,meta_BRAZ$Shannon.het.euk, meta_BRAZ$Shannon.mixo)
plot_correlations(meta_BRAZ,meta_BRAZ$PO4_umol.l, meta_BRAZ$Shannon.het.euk)
plot_correlations(meta_BRAZ,meta_BRAZ$Shannon.auto.cynao, meta_BRAZ$Shannon.het.prok)
plot_correlations(meta_BRAZ,meta_BRAZ$Shannon.auto.euk, meta_BRAZ$Shannon.het.prok)
plot_correlations(meta_BRAZ,meta_BRAZ$SST, meta_BRAZ$Shannon.het.prok)
plot_correlations(meta_SATL_cold,meta_SATL_cold$SST, meta_SATL_cold$Shannon.auto.euk)
plot_correlations(meta_SATL_cold,meta_SATL_cold$Total.N..nmol.L., meta_SATL_cold$Shannon.auto.euk)
plot_correlations(meta_SATL_cold,meta_SATL_cold$distance_to_province_boundary.km., meta_SATL_cold$Shannon.auto.cynao)
plot_correlations(meta_SATL_cold,meta_SATL_cold$Shannon.mixo, meta_SATL_cold$Shannon.auto.euk)
plot_correlations(meta_SATL_cold,meta_SATL_cold$Shannon.mixo, meta_SATL_cold$NO3_umol.l)
plot_correlations(meta_SATL_cold,meta_SATL_cold$Shannon.mixo, meta_SATL_cold$Si_umol.l)
plot_correlations(meta_SATL_cold,meta_SATL_cold$Shannon.mixo, meta_SATL_cold$Shannon.het.euk)
plot_correlations(meta_SATL_hot,meta_SATL_hot$NO3_umol.l, meta_SATL_hot$Shannon.auto.euk)
plot_correlations(meta_SATL_hot,meta_SATL_hot$Shannon.mixo, meta_SATL_hot$Shannon.auto.euk)
plot_correlations(meta_SATL_hot,meta_SATL_hot$Shannon.het.euk, meta_SATL_hot$Shannon.auto.euk)
plot_correlations(meta_SATL_hot,meta_SATL_hot$chlorophyll, meta_SATL_hot$Shannon.het.euk)
plot_correlations(meta_SATL_hot,meta_SATL_hot$Distance_coast.km., meta_SATL_hot$Shannon.het.prok)
plot_correlations(meta_SATL_hot,meta_SATL_hot$chlorophyll, meta_SATL_hot$Shannon.het.prok)
plot_correlations(meta_WTRA,meta_WTRA$Distance_coast.km., meta_WTRA$Shannon.auto.euk)
plot_correlations(meta_WTRA,meta_WTRA$distance_to_province_boundary.km., meta_WTRA$Shannon.auto.euk)
plot_correlations(meta_WTRA,meta_WTRA$PO4_umol.l, meta_WTRA$Shannon.auto.euk)
plot_correlations(meta_WTRA,meta_WTRA$Total.N..nmol.L., meta_WTRA$Shannon.auto.cynao)
plot_correlations(meta_WTRA,meta_WTRA$SST, meta_WTRA$Shannon.mixo)
plot_correlations(meta_WTRA,meta_WTRA$distance_to_province_boundary.km., meta_WTRA$Shannon.het.euk)
plot_correlations(meta_WTRA,meta_WTRA$oxygen.umol.l., meta_WTRA$Shannon.het.euk)
plot_correlations(meta_WTRA,meta_WTRA$distance_to_province_boundary.km., meta_WTRA$Shannon.het.prok)
plot_correlations(meta_WTRA,meta_WTRA$PO4_umol.l, meta_WTRA$Shannon.het.prok)
plot_correlations(meta_NATR,meta_NATR$distance_to_province_boundary.km., meta_NATR$Shannon.het.prok)
plot_correlations(meta_CNRY,meta_CNRY$chlorophyll, meta_CNRY$Shannon.auto.euk)
plot_correlations(meta_CNRY,meta_CNRY$Shannon.auto.cynao, meta_CNRY$Shannon.auto.euk)
plot_correlations(meta_CNRY,meta_CNRY$distance_to_province_boundary.km., meta_CNRY$Shannon.auto.cynao)
plot_correlations(meta_CNRY,meta_CNRY$salinity, meta_CNRY$Shannon.auto.cynao)
plot_correlations(meta_CNRY,meta_CNRY$NO3_umol.l, meta_CNRY$Shannon.auto.cynao)
plot_correlations(meta_CNRY,meta_CNRY$Total.N..nmol.L., meta_CNRY$Shannon.auto.cynao)
plot_correlations(meta_CNRY,meta_CNRY$Shannon.mixo, meta_CNRY$Shannon.auto.cynao)
plot_correlations(meta_CNRY,meta_CNRY$Shannon.mixo, meta_CNRY$Shannon.auto.euk)
plot_correlations(meta_CNRY,meta_CNRY$salinity, meta_CNRY$Shannon.mixo)
plot_correlations(meta_CNRY,meta_CNRY$PO4_umol.l, meta_CNRY$Shannon.mixo)
plot_correlations(meta_CNRY,meta_CNRY$salinity, meta_CNRY$Shannon.het.euk)
plot_correlations(meta_CNRY,meta_CNRY$oxygen.umol.l., meta_CNRY$Shannon.het.prok)
plot_correlations(meta_NAST,meta_NAST$PO4_umol.l, meta_NAST$Shannon.auto.euk)
plot_correlations(meta_NAST,meta_NAST$Si_umol.l, meta_NAST$Shannon.auto.euk)
plot_correlations(meta_NAST,meta_NAST$chlorophyll, meta_NAST$Shannon.auto.euk)
plot_correlations(meta_NAST,meta_NAST$SST, meta_NAST$Shannon.auto.cynao)
plot_correlations(meta_NAST,meta_NAST$PO4_umol.l, meta_NAST$Shannon.auto.cynao)
plot_correlations(meta_NAST,meta_NAST$PO4_umol.l, meta_NAST$Shannon.mixo)
plot_correlations(meta_NADR,meta_NADR$Total.C..nmol.L., meta_NADR$Shannon.auto.euk)
plot_correlations(meta_NADR,meta_NADR$Total.N..nmol.L., meta_NADR$Shannon.auto.cynao)
plot_correlations(meta_NADR,meta_NADR$Shannon.mixo, meta_NADR$Shannon.auto.euk)
plot_correlations(meta_NADR,meta_NADR$Distance_coast.km., meta_NADR$Shannon.het.euk)
plot_correlations(meta_NADR,meta_NADR$Total.C..nmol.L., meta_NADR$Shannon.het.prok)

plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$SST, list_meta$meta_functions.z$Shannon.auto.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$oxygen.umol.l., list_meta$meta_functions.z$Shannon.auto.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Total.C..nmol.L., list_meta$meta_functions.z$Shannon.auto.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Total.N..nmol.L., list_meta$meta_functions.z$Shannon.auto.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$chlorophyll, list_meta$meta_functions.z$Shannon.auto.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$oxygen.umol.l., list_meta$meta_functions.z$Shannon.auto.cynao)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Shannon.mixo, list_meta$meta_functions.z$Shannon.auto.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Shannon.mixo, list_meta$meta_functions.z$Distance_coast.km.)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$SST, list_meta$meta_functions.z$Shannon.mixo)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$oxygen.umol.l., list_meta$meta_functions.z$Shannon.mixo)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Shannon.het.euk, list_meta$meta_functions.z$Shannon.mixo)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Shannon.het.euk, list_meta$meta_functions.z$Shannon.auto.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Shannon.het.prok, list_meta$meta_functions.z$Shannon.het.euk)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Shannon.auto.cynao, list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Shannon.auto.euk, list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$distance_to_province_boundary.km., list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$SST, list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$salinity, list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$oxygen.umol.l., list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$NO3_umol.l, list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$PO4_umol.l, list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Total.C..nmol.L., list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$Total.N..nmol.L., list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta_functions,list_meta$meta_functions.z$chlorophyll, list_meta$meta_functions.z$Shannon.het.prok)
plot_correlations(list_meta$meta.functions.PP.z, list_meta$meta.functions.PP.z$PPAVG, list_meta$meta.functions.PP.z$Shannon.auto.euk)
plot_correlations(list_meta$meta.functions.PP.z, list_meta$meta.functions.PP.z$PPAVG, list_meta$meta.functions.PP.z$Shannon.mixo)
plot_correlations(list_meta$meta.functions.PP.z, list_meta$meta.functions.PP.z$PPAVG, list_meta$meta.functions.PP.z$Shannon.het.euk)





##PP
provinces(list_ASVCounts$ASVCount_auto_cyano.PP.hellinger, list_meta$meta_functions.PP.z)

corr_plot_residuals(list_meta$meta_functions.PP.z[subselection_PP])
plotNormalHistogram(a.residuals$Shannon.auto.euk_PPAVG)
plotNormalHistogram(a.residuals$Shannon.mixo_PPAVG)
plotNormalHistogram(a.residuals$Shannon.het.euk_PPAVG)

corr_plot_residuals(meta_CNRY[subselection_PP]) # change the province subsetting here
plotNormalHistogram(a.residuals$Shannon.auto.euk_PPAVG)
plotNormalHistogram(a.residuals$Shannon.auto.euk_specific_PP)
plotNormalHistogram(a.residuals$Shannon.auto.cynao_PPAVG)
plotNormalHistogram(a.residuals$Shannon.auto.cynao_specific_PP)


plot_correlations(meta_CNRY, meta_CNRY$PPAVG, meta_CNRY$Shannon.auto.euk)
plot_correlations(meta_CNRY, meta_CNRY$specific_PP, meta_CNRY$Shannon.auto.euk)
plot_correlations(meta_CNRY, meta_CNRY$PPAVG, meta_CNRY$Shannon.auto.cynao)
plot_correlations(meta_CNRY, meta_CNRY$specific_PP, meta_CNRY$Shannon.auto.cynao)
